/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomBar: typeof import('./components/common/BottomBar.vue')['default']
    DocumentTitle: typeof import('./components/common/DocumentTitle.vue')['default']
    FIleSubmit: typeof import('./components/FIleSubmit.vue')['default']
    HistoryDialog: typeof import('./components/dialogs/HistoryDialog.vue')['default']
    InnerNavBar: typeof import('./components/common/InnerNavBar.vue')['default']
    InsideNavbar1: typeof import('./components/common/insideNavbar/InsideNavbar1.vue')['default']
    InsideNavbar2: typeof import('./components/common/insideNavbar/InsideNavbar2.vue')['default']
    InsideNavbar3: typeof import('./components/common/insideNavbar/InsideNavbar3.vue')['default']
    InsideNavbar4: typeof import('./components/common/insideNavbar/InsideNavbar4.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    OuterFooter: typeof import('./components/common/outerFooters/OuterFooter.vue')['default']
    OuterFooter2: typeof import('./components/common/outerFooters/OuterFooter2.vue')['default']
    OuterNavbar1: typeof import('./components/common/outerNavbars/OuterNavbar1.vue')['default']
    OuterNavbar2: typeof import('./components/common/outerNavbars/OuterNavbar2.vue')['default']
    OuterNavbar3: typeof import('./components/common/outerNavbars/OuterNavbar3.vue')['default']
    OuterNavbar4: typeof import('./components/common/outerNavbars/OuterNavbar4.vue')['default']
    RegisterForm: typeof import('./components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTag: typeof import('./components/dialogs/SelectTag.vue')['default']
    Sidebar: typeof import('./components/common/sideBar/Sidebar.vue')['default']
    SlugName: typeof import('./components/common/insideNavbar/SlugName.vue')['default']
    SubmitDialog: typeof import('./components/dialogs/SubmitDialog.vue')['default']
    ThankYouDialog: typeof import('./components/dialogs/ThankYouDialog.vue')['default']
  }
}
